kernel: gpio-nct5104d: drop unused variables in nct5104d_gpio_init
Drop unused variables in nct5104d_gpio_init. These variables should have
been dropped in 5b3897ff5534 ("kernel: gpio-nct5104d remove boardname check").
Thix fix compilation warning:
/__w/openwrt/openwrt/openwrt/build_dir/target-x86_64-openwrt-linux-musl_musl/linux-x86_64/gpio-nct5104d/gpio-nct5104d.c: In function 'nct5104d_gpio_init':
/__w/openwrt/openwrt/openwrt/build_dir/target-x86_64-openwrt-linux-musl_musl/linux-x86_64/gpio-nct5104d/gpio-nct5104d.c:413:21: error: unused variable 'board_name' [-Werror=unused-variable]
  413 |         const char *board_name = dmi_get_system_info(DMI_BOARD_NAME);
      |                     ^~~~~~~~~~
/__w/openwrt/openwrt/openwrt/build_dir/target-x86_64-openwrt-linux-musl_musl/linux-x86_64/gpio-nct5104d/gpio-nct5104d.c:412:21: error: unused variable 'board_vendor' [-Werror=unused-variable]
  412 |         const char *board_vendor = dmi_get_system_info(DMI_BOARD_VENDOR);
      |                     ^~~~~~~~~~~~
cc1: all warnings being treated as errors

Fixes: 5b3897ff5534 ("kernel: gpio-nct5104d remove boardname check")
Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>